apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: ingress.yaml
    target:
      version: v1
      kind: Ingress
      name: web-lb
  - path: deployment.yaml
    target:
      version: v1
      kind: Deployment
      name: web-server
