apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
  namespace: webapp
data:
  # FIXME: 作成したDBのユーザー名パスワードをbase64エンコードしたものを設定してください
  # echo -n 'webapp_writer' | base64
  db.user: d2ViYXBwX3dyaXRlcg==
  # echo -n 'ABCDEFG1234567890' | base64
  db.pass: QUJDREVGRzEyMzQ1Njc4OTA=
